<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Directed Pick Slip Picking</name>
   <tag></tag>
   <elementGuidId>d4a36242-46b2-4cce-bc35-c44ce2ad0b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='DirectedPickSlipPicking_Default']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DirectedPickSlipPicking_Default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df88e0d0-f770-45ae-a139-61ce13cc653e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DirectedPickSlipPicking_Default</value>
      <webElementGuid>d16b55de-e03e-4769-8064-b0c2d9e553e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9a8cf4eb-687e-4d27-b2e8-64c5ac46845b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('DirectedPickSlipPicking_Default','')</value>
      <webElementGuid>851ddd5d-d6d8-4d0e-b87f-67c5f9609abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Directed Pick Slip Picking</value>
      <webElementGuid>af44a537-e20d-4b93-8529-4afcb3cadf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DirectedPickSlipPicking_Default&quot;)</value>
      <webElementGuid>ab21a28d-897f-4792-8172-dc9a3dfbb96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='DirectedPickSlipPicking_Default']</value>
      <webElementGuid>bf293fd1-7eca-487b-af68-33f5f84296fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main_menu']/ul/li[3]/a</value>
      <webElementGuid>6a667623-ef44-4634-87f7-3cccdc0ca88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Directed Pick Slip Picking')]</value>
      <webElementGuid>4c8adb27-7678-43b6-8400-75c668b843ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('DirectedPickSlipPicking_Default','')&quot;)]</value>
      <webElementGuid>e613544d-c8bf-4119-a1ba-289f9afe706e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>f684b0a6-078f-4788-81cd-19f859c5214e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'DirectedPickSlipPicking_Default' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;DirectedPickSlipPicking_Default&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Directed Pick Slip Picking' or . = 'Directed Pick Slip Picking')]</value>
      <webElementGuid>21eba35c-5a95-461e-a3dc-4b1529e3ff8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
