<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_List</name>
   <tag></tag>
   <elementGuidId>a51984fa-4470-4ba0-92a7-0ab3102dcfad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnF1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnF1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>574028c8-2486-449d-b410-89d657cb6742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:{}</value>
      <webElementGuid>b6145ca2-c84b-4d28-b04d-e3d37eeaf692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnF1</value>
      <webElementGuid>9ad16b2e-9be2-4311-913f-c1c5c65cd72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('Key').value=112;rfssubmit(); return false;</value>
      <webElementGuid>f456a700-5f55-4a81-8f84-a81900ac0007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contextbutton</value>
      <webElementGuid>2881d20c-b5c9-4c6e-ab48-37060f0ed034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>List</value>
      <webElementGuid>9942f368-52be-4a5a-a890-839609dcfe7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnF1&quot;)</value>
      <webElementGuid>399e8584-a4c8-405e-a5cf-80aa5a763c06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnF1']</value>
      <webElementGuid>7fbbd9de-6a4c-42b6-83f4-4062bb7f9148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article[2]/dl/dd[2]/span/a</value>
      <webElementGuid>0f6978a9-9ef9-48a1-80f0-485ec9e3d398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'List')]</value>
      <webElementGuid>0a42a2b6-0b44-471d-8ce6-47559791d925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:{}')])[3]</value>
      <webElementGuid>dda904af-ab09-4852-9170-e0e8bb37e66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>446489b9-4112-494a-9da1-7675a14b26a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:{}' and @id = 'btnF1' and (text() = 'List' or . = 'List')]</value>
      <webElementGuid>4147513e-b4f4-4ccd-98a6-3eb450dac8ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
