<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txt_1_2_3</name>
   <tag></tag>
   <elementGuidId>2c635a5e-e9cf-48c3-b5a5-792ba488c3f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51895d07-d7d4-4ef4-a1ac-54568cfd7071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>6db3539f-bbf2-4169-a167-3772f67585ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65de5a22-11e8-4fd4-8989-4cc65367cdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>698d7d2d-032d-4863-9de8-877b23631dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_text webbarcode</value>
      <webElementGuid>3acd23a0-f681-450f-b389-ee4c9423dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Number</value>
      <webElementGuid>29df388a-4adc-48aa-98db-7c43396a3067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt&quot;)</value>
      <webElementGuid>e4ea2657-a410-4ccc-99ca-8c413723854d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt']</value>
      <webElementGuid>f80b5cc4-e667-4490-9638-86abbb732f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article[5]/dl/dd/input</value>
      <webElementGuid>8e433834-d366-486b-9194-1c214ea27ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/input</value>
      <webElementGuid>aeb58595-6737-4bfc-80a5-3e3e579d8bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt' and @type = 'text' and @id = 'txt' and @placeholder = 'Item Number']</value>
      <webElementGuid>cd02cf60-cfaf-4bf6-9e6b-4852cf03a9f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
