<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txt</name>
   <tag></tag>
   <elementGuidId>5bff059d-a80a-408c-9f1f-fa6d18e3fbb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9825c372-bd83-45d5-ac1e-1ac76e1f9075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>8b0227bd-aec3-4b51-ab8c-29a0e75a43cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6caa469c-e48a-418c-8aa1-beedba59c44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>c23d1e1f-38dd-4a00-9d95-808eb80d02a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_text webbarcode</value>
      <webElementGuid>3376299a-617e-4e3b-bdc4-049ef30f7fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>default</name>
      <type>Main</type>
      <value>DEV01</value>
      <webElementGuid>139af6fc-fd19-4501-9467-540354ad1ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization Code</value>
      <webElementGuid>3df12e6c-a104-4f19-a681-fd6cb73ffaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt&quot;)</value>
      <webElementGuid>56726a1a-76a6-4817-bc1e-e95d36ff35e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt']</value>
      <webElementGuid>25343310-bf68-4a66-9f6e-b0eccec27d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article/dl/dd/input</value>
      <webElementGuid>b201a38b-e73a-47bf-8329-d1fb56c8bb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/input</value>
      <webElementGuid>d954edeb-d324-4d4a-b342-e27d6ea10da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt' and @type = 'text' and @id = 'txt' and @placeholder = 'Organization Code']</value>
      <webElementGuid>bb9f7b63-77fe-4207-bd1d-2c33542402c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
