<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Procurement</name>
   <tag></tag>
   <elementGuidId>7221cb35-c468-4cd9-ab45-ba2972eb3bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#groupNode_procurement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='groupNode_procurement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>defc0bd3-85ae-4f3b-b237-db7a618d44da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9b22a4b9-1c45-4b1e-810e-38907b53180a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupNode_procurement</value>
      <webElementGuid>b7e5cbb1-ef3f-473d-99c8-20a1ac78f02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupNode_procurement</value>
      <webElementGuid>23188f15-e56c-499e-bcb6-811305e4dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0fd0e529-355a-417a-8a5f-4f78b5e22715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flat-tabs-text</value>
      <webElementGuid>5c6131d8-993d-43f9-b16c-e98a37cc05bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d2a3ab60-d1ce-4bc4-8e79-dd5c36d158ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procurement</value>
      <webElementGuid>b4d09e4d-e8eb-41b9-89ed-09d4d0991a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupNode_procurement&quot;)</value>
      <webElementGuid>e5da347a-00bf-4d69-b1a4-621285a9520b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='groupNode_procurement']</value>
      <webElementGuid>20763338-dbc9-4447-9ab8-ca66a08d3bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navmenu-container']/div[22]/a</value>
      <webElementGuid>ae115a9f-459c-48ec-b5a4-63b21f35698c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Procurement')]</value>
      <webElementGuid>8cb3e0b0-4d1f-40f8-aa55-3e1a7b487280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[40]</value>
      <webElementGuid>c8958fba-e96f-4e46-925e-47b3f3d458ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/a</value>
      <webElementGuid>80ae0809-3813-4931-8a33-cbd2d4e60ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'groupNode_procurement' and @name = 'groupNode_procurement' and (text() = 'Procurement' or . = 'Procurement')]</value>
      <webElementGuid>fe377c6d-3a7b-41e6-bfee-dd8b0cce2600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
