<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Sign In</name>
   <tag></tag>
   <elementGuidId>bf85fe7e-474a-4b1f-ae5b-dc3eee53acd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnActive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnActive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66bd5821-e0ef-47e3-a03f-9abada09553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btnActiveChooser unemphasized signinWidth</value>
      <webElementGuid>a074c658-b315-46d3-891a-03ff04378a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d08c8cd-7e0f-4c19-9539-10f1d56ea032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnActive</value>
      <webElementGuid>b04d76e5-c3ff-489f-9fe1-5ad9946c5458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onClickSubmit('local');</value>
      <webElementGuid>6946c34f-065f-43cd-86f9-f3ff8bf733e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In </value>
      <webElementGuid>3bf5c22b-1cfb-4466-903e-bd2014b3a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnActive&quot;)</value>
      <webElementGuid>338a64f7-b28c-41ac-8fd4-8ec8052618a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnActive']</value>
      <webElementGuid>87400928-ed81-45b0-9cbb-4d03efd07e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Login']/div[2]/div[4]/button</value>
      <webElementGuid>50479e3f-4411-46a7-a58f-546e14bebf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>290e5356-e1a6-488c-bcf0-33d9bcb34bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnActive' and (text() = 'Sign In ' or . = 'Sign In ')]</value>
      <webElementGuid>05223836-9808-447e-90aa-0cb9b4b6503b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
