<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_Option_Midtown Computer Supplies 10001</name>
   <tag></tag>
   <elementGuidId>79a969e5-b772-4f3f-a568-2b0077fd8961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::su0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4e64e391-da84-4bb9-a2cf-70e040f84e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1b5adfa4-7174-4866-bc35-064c131a8bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::su0</value>
      <webElementGuid>bf8c1d21-59ac-4532-9f99-ff8854b060e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-afr-value</name>
      <type>Main</type>
      <value>Midtown Computer Supplies</value>
      <webElementGuid>5ebf6f19-884f-4bdd-8e8a-81a403764b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-afr-label</name>
      <type>Main</type>
      <value>Midtown Computer Supplies 10001  </value>
      <webElementGuid>ffb6fda5-9f10-42a7-9d65-4d5d8c86380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AFAutoSuggestItem</value>
      <webElementGuid>f03327c2-a0c8-4f48-a981-517dc55a45f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Midtown Computer Supplies 10001  </value>
      <webElementGuid>03abacdd-8a4d-4523-bcef-37d6f0d0156b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::su0&quot;)</value>
      <webElementGuid>0336ecca-35d0-4203-946e-b6e9395ce5b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::su0']</value>
      <webElementGuid>a106351d-8c97-4d1a-840a-003f8ae63f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::_afrautosuggestpopup']/li</value>
      <webElementGuid>a9172ab9-88f4-4261-b803-733a2f5aedb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/ul/li</value>
      <webElementGuid>656ec9a5-aa3a-472a-b3a0-fd8f22eae39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '_FOpt1:_FOr1:0:_FONSr2:0:_FOTRaT:0:dynam1:0:Supplier::su0' and (text() = 'Midtown Computer Supplies 10001  ' or . = 'Midtown Computer Supplies 10001  ')]</value>
      <webElementGuid>beee614c-73f6-4311-bd12-cb36a23085c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
