<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Purchase Orders</name>
   <tag></tag>
   <elementGuidId>b95b9231-80fa-4923-ba21-81c2f1bb2c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itemNode_procurement_PurchaseOrders</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itemNode_procurement_PurchaseOrders']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5dff357a-ab70-43fe-b6f8-0cb731061257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itemNode_procurement_PurchaseOrders</value>
      <webElementGuid>f11cd985-169a-4e4e-a3da-df3d061fa087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-nav-item</value>
      <webElementGuid>64d0e8bc-b30e-48fc-89de-f7a438f4c46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>filmstrip</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>fdda80eb-ca4b-4968-b49e-43f6484e9c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>page</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>88192385-562e-442a-8968-7febfd95570f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d620357e-f886-4f95-88bf-b3ff5d3e101a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>subcluster</value>
      <webElementGuid>9746e8fe-3177-4371-a3e2-312c8e3c5087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>20469ef7-f982-4051-b477-c48d90426f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>groupNode_procurement</value>
      <webElementGuid>275b3cf7-8cf7-4455-aab1-b9395920772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>destinationurl</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>33d5e009-9176-444f-ae9c-a8f20f024aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>targetframe</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6b58eb9d-dc5d-44ab-8383-78ba48ca0a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isdesturlexist</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>174d82ae-613c-4ff0-a639-bd38d8d6e0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>bd5f8c04-cd37-4f05-a6ad-668203b70ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>996106db-4d9f-4ec1-a3aa-10e0549cc49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemNode_procurement_PurchaseOrders&quot;)</value>
      <webElementGuid>6054b222-04a2-4b1b-b62c-41dfbb1f5441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='itemNode_procurement_PurchaseOrders']</value>
      <webElementGuid>43ce4ed1-b55f-418a-ad9b-23ae72d3a8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yourapps_groupNode_procurement']/div[3]/div</value>
      <webElementGuid>f9b6d5cd-d3dc-4400-bbfd-d67c9433389d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[43]/div/div[2]/div[2]/div[3]/div</value>
      <webElementGuid>fc90ecf1-4f4e-405e-b57d-c087fac52ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'itemNode_procurement_PurchaseOrders' and @type = 'subcluster' and @title = 'Purchase Orders' and (text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      <webElementGuid>4be9c6fd-5a14-48ec-91aa-5fe8e563e33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
