<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Procurement</name>
   <tag></tag>
   <elementGuidId>251fcc90-3849-400b-ace1-3d8840101b15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pt1:_UISnvr:0:nvgpgl2_groupNode_procurement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2caef3f-a015-46d5-ac98-f53c967c13d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_UISnvr:0:nvgpgl2_groupNode_procurement</value>
      <webElementGuid>3b4bf230-3731-4331-b14f-26effe8800f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Procurement</value>
      <webElementGuid>0f768484-c5b0-4978-afe9-d9d4a4cc7e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p_AFHoverTarget navmenu-header x1a</value>
      <webElementGuid>eeb7ceb1-cdb1-42ec-a025-22d063078e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Procurement </value>
      <webElementGuid>08c205db-646f-414d-81bf-fe303f7143ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UISnvr:0:nvgpgl2_groupNode_procurement&quot;)</value>
      <webElementGuid>78e2b552-f369-42c0-90f0-3085607d4b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pt1:_UISnvr:0:nvgpgl2_groupNode_procurement']</value>
      <webElementGuid>88820259-64d1-4623-9a69-ede34e8f141b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pt1:_UISnvr:0:nvgpgl1_groupNode_procurement']/div/div</value>
      <webElementGuid>8dc37477-1b67-4cae-8f72-01e7e8790c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div/div</value>
      <webElementGuid>92dfea89-6dd2-4644-85d1-03f6fd9b7386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pt1:_UISnvr:0:nvgpgl2_groupNode_procurement' and @title = 'Procurement' and (text() = 'Procurement ' or . = 'Procurement ')]</value>
      <webElementGuid>5ee7a065-a432-4224-8967-022801e73eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
