<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PurchaseOrders</name>
   <tag></tag>
   <elementGuidId>4566f16c-4392-4f1b-8261-42fa1700d2b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>84c92deb-68e6-4ba1-960f-49b7f58fc70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xmt</value>
      <webElementGuid>1c2b35dd-d063-4a70-8f8e-7052e7f7d513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Purchase Orders</value>
      <webElementGuid>72b4bf0b-0593-45b2-bd72-a2841791975e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders&quot;)/span[@class=&quot;xmt&quot;]</value>
      <webElementGuid>b6aab2ef-df00-4fd2-8c9f-caa977e49b27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders']/span</value>
      <webElementGuid>1d1d0617-b577-4279-bc8e-cca0c662ddbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div[2]/div/div[3]/a/span</value>
      <webElementGuid>0d888847-0f68-4dbd-81b4-67b46509d5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Purchase Orders' or . = 'Purchase Orders')]</value>
      <webElementGuid>379214c1-c28c-4dac-8aed-226a17c2f012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
