<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svgpt1_UISnvr0nv_itemNode_procurement_Purch_95d69d</name>
   <tag></tag>
   <elementGuidId>f3d19219-1f4b-4db1-a1b1-a6ddcafc6f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//svg[@id = 'pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders::icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>94bba3ce-453a-4566-86c5-7360eaebb27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>fb04db55-d16e-481a-abb7-7add707f2353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-bkgd07 xi6</value>
      <webElementGuid>03f8bc71-4e3f-486b-82e4-19f7cd74dbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>54859c96-2985-47c9-89c1-4f5b712e914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>25e7d842-1340-4a19-9d1f-d868beec89f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 48 48</value>
      <webElementGuid>ddbcb189-740a-4fa5-a8ab-4a8d2a598f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders::icon</value>
      <webElementGuid>efa2ff78-06c0-4839-b045-f63b81b44b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_afrsvg</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26a6bb20-672b-4903-a4b8-9174787494e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders::icon&quot;)</value>
      <webElementGuid>67ff096a-ed32-4a5b-ab33-62a30fdff376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'pt1:_UISnvr:0:nv_itemNode_procurement_PurchaseOrders::icon']</value>
      <webElementGuid>40037a85-2b33-4004-9577-21280d6fd441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
