<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ReqDate2</name>
   <tag></tag>
   <elementGuidId>ff816245-d269-47d2-a3b4-f8ea01093b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_FOpt1\:_FOr1\:0\:_FONSr2\:0\:MAt2\:0\:AP1\:AT1\:_ATp\:Lines\:1\:NeedByDate\:\:content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
