<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_POLinePrice2</name>
   <tag></tag>
   <elementGuidId>3b88b994-7854-4711-953a-8be15e68f129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_FOpt1\:_FOr1\:0\:_FONSr2\:0\:MAt2\:0\:AP1\:AT1\:_ATp\:Lines\:1\:UnitPrice\:\:content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
