<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ItemNum2</name>
   <tag></tag>
   <elementGuidId>a16a9821-e0ac-4692-bb56-b9c8be1b3e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_FOpt1\:_FOr1\:0\:_FONSr2\:0\:MAt2\:0\:AP1\:AT1\:_ATp\:Lines\:1\:Item\:\:content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
