<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_POLineQty2</name>
   <tag></tag>
   <elementGuidId>fc63f1b6-8873-4d73-b643-fbd59e33906c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_FOpt1\:_FOr1\:0\:_FONSr2\:0\:MAt2\:0\:AP1\:AT1\:_ATp\:Lines\:1\:s5\:Quantity\:\:content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
