<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>fa0e11ef-6bdd-4b30-a9bf-02ff6c4841c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEnter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnEnter'] | /html/body/div[2]/div/div[2]/div/div/div[2]/form/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d1a1d08-a330-41f9-b605-f210efb97921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:{}</value>
      <webElementGuid>bf76413b-e1e2-48d5-98c9-db2c06118b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEnter</value>
      <webElementGuid>020d1c98-7bc2-40df-a7b8-8fe403a2cc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('Key').value=13;rfssubmit(); return false;</value>
      <webElementGuid>ca0899a8-7ff2-4f05-95ea-d149a7ec8daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contextbutton</value>
      <webElementGuid>eb49f7aa-7cfa-4d76-904e-e702e45f614b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>7dd2c019-c566-4bb4-9d28-3591cada7e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEnter&quot;)</value>
      <webElementGuid>905f0cbc-5bcd-4d81-ad1d-dfec97661dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnEnter']</value>
      <webElementGuid>e93ce8da-e031-4fc5-ba3b-bfd20a1f97d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article[2]/dl/dd[2]/span/a</value>
      <webElementGuid>5a46ab48-4b07-4d80-8137-33d0aae5b917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter')]</value>
      <webElementGuid>a1c3b5b8-4987-47c0-9394-7fee4ea07cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:{}')]</value>
      <webElementGuid>8cdba16d-ec7e-44a9-8e67-8394d5408336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e1fbfb88-f8ba-4899-9c84-9ba19550ecb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:{}' and @id = 'btnEnter' and (text() = 'Enter' or . = 'Enter')]</value>
      <webElementGuid>625114f5-b64a-4167-af23-72195a55cfa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
