<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Enter</name>
   <tag></tag>
   <elementGuidId>fa0e11ef-6bdd-4b30-a9bf-02ff6c4841c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnEnter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnEnter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a77c9911-7d21-4ee3-b865-3b01851ce17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:{}</value>
      <webElementGuid>693a4604-9c55-4c30-a713-d5bfdf6208f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEnter</value>
      <webElementGuid>6da31a9b-bb0c-4c34-933d-03bae22a58d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('Key').value=13;rfssubmit(); return false;</value>
      <webElementGuid>b9f7ccf6-2978-439f-9277-a1a67ece8cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contextbutton</value>
      <webElementGuid>ccf7014e-3fe6-496f-8254-c99545a712ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>4640f65c-86c3-4fe6-88d5-0dd523c92b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEnter&quot;)</value>
      <webElementGuid>183aa84b-1769-47a1-a92b-5f4825c7fc75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnEnter']</value>
      <webElementGuid>8ea3a38a-dbe3-40ff-bf52-d6ed4f4a9029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article[2]/dl/dd[2]/span/a</value>
      <webElementGuid>1d6a7e02-4c27-4e23-a905-4e285854e647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter')]</value>
      <webElementGuid>731dda53-a7b6-4f28-9833-22371e3e5cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:{}')]</value>
      <webElementGuid>1052d2a2-b91d-44a4-b4bc-b36a7d2ed619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>83c0aa00-9c81-4bea-80d2-1945d3c63d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:{}' and @id = 'btnEnter' and (text() = 'Enter' or . = 'Enter')]</value>
      <webElementGuid>2864f77b-9594-4d0c-b6e9-bf38a128a459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
