<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Miscellaneous Transactions</name>
   <tag></tag>
   <elementGuidId>0561abfa-4ef8-414c-b98a-c645c9134d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MiscellaneousTransactions_Default']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MiscellaneousTransactions_Default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22fab429-0e55-4f84-b417-b10b12c6cdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MiscellaneousTransactions_Default</value>
      <webElementGuid>bb4800ba-21b3-4c7f-bdda-ac7100e87738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>fc1b08c3-ebb8-4526-810d-907e5861e4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('MiscellaneousTransactions_Default','')</value>
      <webElementGuid>afbf1292-f73b-4273-bd71-3400a077a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Miscellaneous Transactions</value>
      <webElementGuid>56862834-1997-4afa-8d3d-3f9f0792a478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MiscellaneousTransactions_Default&quot;)</value>
      <webElementGuid>70e8e1a8-32fe-40c9-bd01-7a9983de2aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MiscellaneousTransactions_Default']</value>
      <webElementGuid>9ad5ee87-d03c-41df-bf0f-605bd7db4b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main_menu']/ul/li[6]/a</value>
      <webElementGuid>b6df5032-6e97-4a7a-b398-3b211b55ac9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Miscellaneous Transactions')]</value>
      <webElementGuid>2bf84048-473f-48b1-bb92-73ebecdfcb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('MiscellaneousTransactions_Default','')&quot;)]</value>
      <webElementGuid>aeb4a8f2-bc90-4c04-ac80-9bb351aebba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>12c85c4b-84ba-4d56-a25b-697a0821cfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MiscellaneousTransactions_Default' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;MiscellaneousTransactions_Default&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Miscellaneous Transactions' or . = 'Miscellaneous Transactions')]</value>
      <webElementGuid>600c1fb2-8b08-4ab4-ab9f-5afe83e838cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
