<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Pick Confirm</name>
   <tag></tag>
   <elementGuidId>c1b4e79c-dd35-4296-9592-e68e07f3f0dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='PickConfirm_Default']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PickConfirm_Default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e9908c8-55fc-441b-b767-c106c91b17ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PickConfirm_Default</value>
      <webElementGuid>9bdfdb31-2391-4041-9a4d-3ac040962d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>cc6f1920-3fe9-45a6-9854-2939026998e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('PickConfirm_Default','')</value>
      <webElementGuid>5fe84a23-fb93-4623-a3ab-759b479660de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick Confirm</value>
      <webElementGuid>79cffea1-001b-4b96-8fdd-5c1dbfa5119d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PickConfirm_Default&quot;)</value>
      <webElementGuid>69e616fd-b36c-4a1e-ae56-646cc91634f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='PickConfirm_Default']</value>
      <webElementGuid>3a62354d-ccd5-4ecf-88bf-7fd5f7789cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main_menu']/ul/li[9]/a</value>
      <webElementGuid>1d503c61-da85-4748-90ce-0f385aeab8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pick Confirm')]</value>
      <webElementGuid>c2dcbe64-557b-4034-b2e5-ff4780476a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('PickConfirm_Default','')&quot;)]</value>
      <webElementGuid>8d114608-aba5-4a98-8881-829b60fca191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>7de7f9d5-4214-4d5b-8547-3de677525605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'PickConfirm_Default' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;PickConfirm_Default&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Pick Confirm' or . = 'Pick Confirm')]</value>
      <webElementGuid>7319c0e9-591d-4970-b276-6ed2f412a217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
