<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_Account Alias Issue 02</name>
   <tag></tag>
   <elementGuidId>f19aeb4a-abeb-4f35-aee5-0e8407e3c1b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AccountAliasIssue02_Default']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountAliasIssue02_Default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b20aa181-78b8-4ad9-9b74-e1a426f56e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountAliasIssue02_Default</value>
      <webElementGuid>46b22fb5-9875-4553-9ca1-29c316900fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ff9ca8c9-d916-444b-828f-a0441e96beaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('AccountAliasIssue02_Default','')</value>
      <webElementGuid>ed125d96-160d-4c0b-84f3-ba93fef4812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Alias Issue 02</value>
      <webElementGuid>f505568c-375c-4522-8909-a2f172ddffda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountAliasIssue02_Default&quot;)</value>
      <webElementGuid>9931451d-425e-4641-8f6a-54ac2a90a01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='AccountAliasIssue02_Default']</value>
      <webElementGuid>c9481a03-5b86-4f83-b8ec-20dfa5b88f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main_menu']/ul/li[2]/a</value>
      <webElementGuid>39fbd6a8-308e-4ab0-8ba9-83a531dc700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Account Alias Issue 02')]</value>
      <webElementGuid>43e4a1c7-a0e8-4c12-ae25-7307ea8f61cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('AccountAliasIssue02_Default','')&quot;)]</value>
      <webElementGuid>658796fd-6b9c-4695-b412-5741ca1980ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/ul/li[2]/a</value>
      <webElementGuid>8fcc4d2b-d547-4c2d-aba8-ad59b2c4e23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'AccountAliasIssue02_Default' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;AccountAliasIssue02_Default&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Account Alias Issue 02' or . = 'Account Alias Issue 02')]</value>
      <webElementGuid>0e84a6b0-ff62-4128-bd2f-0fd2c8a81551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
