<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_UOM</name>
   <tag></tag>
   <elementGuidId>3ad562f6-bcac-4f1c-ae8e-b533ea11330c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eebea1e-6dec-4087-b9cb-04d048ddc734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>3dacf5ff-35a9-41c4-beeb-ff00efdec07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56a37221-19b9-4a83-9333-31cf18c551c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>e5471837-f1d2-45f2-b180-6308cdd27424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_text webbarcode</value>
      <webElementGuid>ab8f7a72-f6cc-42e2-ae73-1afeca8c8878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>default</name>
      <type>Main</type>
      <value>Ea</value>
      <webElementGuid>3937f2d6-7657-4629-a0f7-f78904f9c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>UOM</value>
      <webElementGuid>aeb231bb-b13e-4339-8b2a-7960d9f5c0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt&quot;)</value>
      <webElementGuid>0a533246-c148-41be-8911-8b0974f43abb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt']</value>
      <webElementGuid>8232be72-4ffe-4686-bb88-0b3fb464af07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article[3]/dl/dd/input</value>
      <webElementGuid>79cee3e2-dce2-4144-8d52-ad5d14674a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/input</value>
      <webElementGuid>3cd6274e-432c-4cbb-aed9-047b48c139b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txt' and @type = 'text' and @id = 'txt' and @placeholder = 'UOM']</value>
      <webElementGuid>23f5b5e4-c5b3-4a36-9cf9-2baea3995107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
