<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Username</name>
   <tag></tag>
   <elementGuidId>7ea5c49f-40f9-46ef-b49a-7c78fe096c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd5faf2d-bff2-4018-962f-81da8ba74320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtUser</value>
      <webElementGuid>3b1cc46f-ff62-43c1-ac8e-541003992687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebca1b16-1384-4424-b6d8-9856653661e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUser</value>
      <webElementGuid>902306b5-39ca-4b43-afb3-481e363e04ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_text webbarcode</value>
      <webElementGuid>b5409f58-856d-446a-bd21-54907bffc5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dditem</name>
      <type>Main</type>
      <value>User</value>
      <webElementGuid>4038528c-d484-4b67-8428-41acdff18206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User ID</value>
      <webElementGuid>9c81b087-ff14-441a-a258-a406126f88a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUser&quot;)</value>
      <webElementGuid>f0e81b05-d05d-4a26-8cca-4a2916a292d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtUser']</value>
      <webElementGuid>3aadfb1a-2f06-47b6-8143-c9bd9a43b60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='application']/article/dl/dd/input</value>
      <webElementGuid>95279025-5432-4b59-b52b-f86f3b79f8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/input</value>
      <webElementGuid>b351d948-71ca-406c-9559-8b631bb20ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtUser' and @type = 'text' and @id = 'txtUser' and @placeholder = 'User ID']</value>
      <webElementGuid>61fc12b5-1670-4687-810d-37e7605278ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
